# Generated by Django 4.2.16 on 2024-09-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videoapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="video_file",
            new_name="file",
        ),
    ]
