# Generated by Django 4.2.16 on 2024-09-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videoapp", "0002_rename_video_file_video_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="file",
            new_name="video_file",
        ),
    ]
