services:
  web:
    build: .
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - .:/code
  web_migrate:
    extends:
      service: web
    command: python /code/videoprocessor/manage.py migrate
    depends_on:
      - db
  web_run:
    extends:
      service: web
    command: python /code/videoprocessor/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - web_migrate
  db:
    image: postgres:14.13
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres